spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d13iqdogjchc738to900-a.oregon-postgres.render.com:5432/inventario_4ah1
    username: inventario_4ah1_user
    password: U59ytq61sSviY8oEFHSG4iaeH1pGQPOB
